# Generated by Django 5.0.1 on 2024-01-24 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1000), django.core.validators.MaxValueValidator(limit_value=9999)]),
        ),
    ]
