# Generated by Django 5.0.1 on 2024-01-24 07:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_qualification_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 1, 24)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 1, 31))]),
        ),
    ]
